version: '3.8'

services:
  findash-ai:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-findash-secret-key-2024}
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./samples:/app/samples
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  findash-ai-dev:
    build: .
    ports:
      - "5002:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-findash-secret-key-2024}
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./samples:/app/samples
    command: ["python", "app.py"]
    profiles:
      - dev
